project_id = "gobuakgvzqauzenaswow"

[functions.ftc-rascunho]
verify_jwt = false

[functions.ftc-import]
verify_jwt = false

[functions.send-email-with-pdf]
verify_jwt = false

[functions.improve-description]
verify_jwt = false